#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_home:
    path: /
    controller: App\Controller\Home::say
app_contact:
    path: /contact
    controller: App\Controller\Contact::say